### ISSUE TITLE
IHEAuditor throws  Unhandled exception type CloneNotSupportedException

### ISSUE THREAD

**Issue by cyrillzadra** [oehf/ipf-oht-auditor#2]
Since AuditorModuleConfig clone() uses super.clone() and throws CloneNotSupportedException there is now an compiler error in AuditorFactory.

"Unhandled exception type CloneNotSupportedException"

**Comment by unixoid** [comment]
Sorry for the confusion, but ipf-oht-auditor is an obsolete project, we should have removed it.  The actually maintained one is ipf-oht-atna.  Could you please check whether the error exists there as well?  Thank you.

**Comment by cyrillzadra** [comment]
Everything works fine when I use https://github.com/oehf/ipf-oht-atna  repository :). Thanks for helping out.
